# AWS CloudFormation Stack that creates two buckets and a IAM user to
# make uploads to both buckets.
# The first bucket is intended to be used for Deep Archive files.
# The second is for Instant Retrival files.

# Based on https://github.com/m-radzikowski/aws-s3-personal-backup


AWSTemplateFormatVersion: 2010-09-09

Resources:
  BackupBucketDeep:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: Knox
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced # The owner of the bucket is also the owner of the objects
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: AbortIncompleteMultipartUpload # If an object is not totally uploaded, after 2 days the part that was uploaded will be deleted
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 2

  BackupBucketInstant:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ClipKiller
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced # The owner of the bucket is also the owner of the objects
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: AbortIncompleteMultipartUpload # If an object is not totally uploaded, after 2 days the part that was uploaded will be deleted
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 2
          - Id: NoncurrentVersionExpiration # Keep three versions of an object for thirty days
            Status: Enabled
            NoncurrentVersionExpiration:
              NewerNoncurrentVersions: 3
              NoncurrentDays: 30

  BackupUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: s3-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*MultipartUpload*"
                  - "s3:ListBucket"
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource:
                  - !Sub '${BackupBucketDeep.Arn}'
                  - !Sub '${BackupBucketDeep.Arn}/*'
                  - !Sub '${BackupBucketInstant.Arn}'
                  - !Sub '${BackupBucketInstant.Arn}/*'
